### ISSUE TITLE
App Crash: OOM issue on phone and Simulator

### ISSUE THREAD

**Issue by ddesai** [ddesai/amapp-android#11]
When user switches around from one screen to another - e.g. ThakorjiToday --> SahebjiDarshan --> Audio --> SahebjiDarshan --> etc, it runs into the OOM issue and app crashes

12-13 09:15:23.182 2038-2038/com.amapp E/art: Throwing OutOfMemoryError "Failed to allocate a 45411852 byte allocation with 4194304 free bytes and 36MB until OOM"
12-13 09:15:23.182 2038-2038/com.amapp D/skia: --- allocation failed for scaled bitmap
12-13 09:15:23.182 2038-2038/com.amapp D/AndroidRuntime: Shutting down VM
12-13 09:15:23.184 2038-2038/com.amapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                         Process: com.amapp, PID: 2038
                                                         java.lang.OutOfMemoryError: Failed to allocate a 45411852 byte allocation with 4194304 free bytes and 36MB until OOM
                                                             at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                             at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                             at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
                                                             at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
                                                             at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:988)
                                                             at android.content.res.Resources.loadDrawableForCookie(Resources.java:2474)
                                                             at android.content.res.Resources.loadDrawable(Resources.java:2381)
                                                             at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
                                                             at android.widget.ImageView.<init>(ImageView.java:146)
                                                             at android.widget.ImageView.<init>(ImageView.java:135)
                                                             at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:60)
                                                             at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:56)
                                                             at android.support.v7.internal.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:98)
                                                             at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:926)
                                                             at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:980)
                                                             at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                             at com.amapp.thakorjitoday.TempleListFragment$TempleAdapter.onCreateViewHolder(TempleListFragment.java:109)
                                                             at com.amapp.thakorjitoday.TempleListFragment$TempleAdapter.onCreateViewHolder(TempleListFragment.java:89)
                                                             at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5223)
                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4449)
                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)
                                                             at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
                                                             at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
                                                             at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
                                                             at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
                                                             at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
                                                             at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
                                                             at android.view.View.layout(View.java:15671)
                                                             at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                             at android.view.View.layout(View.java:15671)
                                                             at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                             at android.view.View.layout(View.java:15671)
                                                             at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                             at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                                                             at android.view.View.layout(View.java:15671)
                                                             at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                             at android.view.View.layout(View.java:15671)
                                                             at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                             at android.view.View.layout(View.java:15671)
                                                             at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                         	at android.support.v4.widget.DrawerLayout.onLayout(

**Comment by ddesai** [comment]
Changing the emulator AVD heap size to 128MB helped. Now it seems to work fine.

**Comment by ddesai** [comment]
Closing this issue. Please re-open if needed

**Comment by patelankur1210** [comment]
This is the setting to change - 
![image](https://cloud.githubusercontent.com/assets/6286542/11917204/ff8e78be-a6b1-11e5-87f8-ffe9f1f9f728.png)

**Comment by shanunigam** [comment]
This is the setting to change - 
![image](https://cloud.githubusercontent.com/assets/6286542/11917204/ff8e78be-a6b1-11e5-87f8-ffe9f1f9f728.png)
